services:
  oracle:
    image: gvenzl/oracle-free:23-slim-faststart
    container_name: parking-db
    restart: always
    environment:
      ORACLE_PASSWORD: admin123
      APP_USER: parkingapp
      APP_USER_PASSWORD: admin123
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./backend/init-oracle:/container-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle_data:
